#!/usr/bin/env ruby
# frozen_string_literal: true

# Standalone Android NDK cross-compile of Nokogiri's C extension.
# Does NOT build Ruby. Uses staged Termux headers/libs + NDK clang.
#
# Env (from setup.sh): STAGE_DIR, GEM_PLATFORM, RUBY_API, CC, AR, ...

require "fileutils"
require "rbconfig"
require "shellwords"

def need!(key)
  val = ENV[key]
  abort "missing env #{key}" if val.nil? || val.empty?
  val
end

stage = need!("STAGE_DIR")
gem_platform = need!("GEM_PLATFORM")
ruby_api = need!("RUBY_API")
cc = need!("CC")
ar = need!("AR")
root = need!("NOKOGIRI_ANDROID_ROOT")
host_ruby = RbConfig.ruby

nokogiri_src = if File.directory?(File.join(root, "nokogiri", "ext", "nokogiri"))
  File.join(root, "nokogiri")
elsif File.directory?(File.join(root, "ext", "nokogiri"))
  root
else
  abort "cannot find nokogiri sources under #{root}"
end

ext_dir = File.join(nokogiri_src, "ext", "nokogiri")
abort "missing #{ext_dir}" unless File.directory?(ext_dir)

# Clean previous products
%w[Makefile nokogiri.so nokogiri.bundle mkmf.log].each { |f| FileUtils.rm_f(File.join(ext_dir, f)) }
Dir.glob(File.join(ext_dir, "*.o")).each { |f| FileUtils.rm_f(f) }
FileUtils.rm_rf(File.join(ext_dir, "tmp"))
# Keep ports/ if gumbo already built for this arch? Clean to avoid host-arch mixups.
FileUtils.rm_rf(File.join(ext_dir, "ports"))

rbconfig_candidates = Dir.glob(File.join(stage, "lib", "ruby", ruby_api, "*", "rbconfig.rb"))
rbconfig_path = rbconfig_candidates.find { |p| File.basename(File.dirname(p)) == gem_platform } ||
  rbconfig_candidates.find { |p| p.include?("linux-android") } ||
  rbconfig_candidates.first
abort "no rbconfig.rb under #{stage}/lib/ruby/#{ruby_api}" unless rbconfig_path && File.file?(rbconfig_path)

ruby_hdr = ENV.fetch("RUBY_HDR")
ruby_arch_hdr = ENV.fetch("RUBY_ARCH_HDR")
cxx = ENV.fetch("CXX", cc)
ranlib = ENV.fetch("RANLIB", File.join(File.dirname(ar), "llvm-ranlib"))
strip = ENV.fetch("STRIP", File.join(File.dirname(ar), "llvm-strip"))
ld = ENV.fetch("LD", cc)

# Write a -r preload that rewrites RbConfig for Android cross-compile.
# Must run as separate process so mkmf sees $0 == extconf.rb (correct srcdir).
preload = File.join(root, "scripts", ".android_rbconfig_preload.rb")
File.write(preload, <<~PRELOAD)
  # frozen_string_literal: true
  # Auto-generated by cross_compile.rb — Android RbConfig patcher.
  require "rbconfig"
require "shellwords"

  load #{rbconfig_path.inspect}

  stage = #{stage.inspect}
  termux_prefix_re = %r{/data/data/[^/]+/files/usr}
  %w[CONFIG MAKEFILE_CONFIG].each do |const|
    conf = RbConfig.const_get(const)
    conf.each do |k, v|
      next unless v.is_a?(String)
      conf[k] = v.gsub(termux_prefix_re, stage)
    end
  end

  cc = #{cc.inspect}
  cxx = #{cxx.inspect}
  ar = #{ar.inspect}
  ld = #{ld.inspect}
  ranlib = #{ranlib.inspect}
  strip = #{strip.inspect}
  ruby_hdr = #{ruby_hdr.inspect}
  ruby_arch_hdr = #{ruby_arch_hdr.inspect}
  host_ruby = #{host_ruby.inspect}
  arch_name = #{File.basename(File.dirname(rbconfig_path)).inspect}

  {
    "CC" => cc,
    "CXX" => cxx,
    "LD" => ld,
    "AR" => ar,
    "RANLIB" => ranlib,
    "STRIP" => strip,
    "CPP" => "\#{cc} -E",
    "CXXCPP" => "\#{cxx} -E",
    "NULLCMD" => ":",
  }.each { |k, v| RbConfig::CONFIG[k] = RbConfig::MAKEFILE_CONFIG[k] = v }

  RbConfig::CONFIG["rubyhdrdir"] = RbConfig::MAKEFILE_CONFIG["rubyhdrdir"] = ruby_hdr
  RbConfig::CONFIG["rubyarchhdrdir"] = RbConfig::MAKEFILE_CONFIG["rubyarchhdrdir"] = ruby_arch_hdr
  RbConfig::CONFIG["libdir"] = RbConfig::MAKEFILE_CONFIG["libdir"] = File.join(stage, "lib")
  RbConfig::CONFIG["arch"] = RbConfig::MAKEFILE_CONFIG["arch"] = arch_name
  RbConfig::CONFIG["sitearch"] = RbConfig::MAKEFILE_CONFIG["sitearch"] = arch_name
  RbConfig::CONFIG["DLEXT"] = RbConfig::MAKEFILE_CONFIG["DLEXT"] = "so"
  RbConfig::CONFIG["SOEXT"] = RbConfig::MAKEFILE_CONFIG["SOEXT"] = "so"
  # Host ruby for make recipes that invoke $(RUBY) (clean-ports disabled, but keep safe)
  RbConfig::CONFIG["ruby_install_name"] = RbConfig::MAKEFILE_CONFIG["ruby_install_name"] = File.basename(host_ruby)
  RbConfig::CONFIG["RUBY"] = host_ruby
  RbConfig::CONFIG["bindir"] = RbConfig::MAKEFILE_CONFIG["bindir"] = File.dirname(host_ruby)

  %w[CFLAGS CPPFLAGS LDFLAGS DLDFLAGS].each do |flag_key|
    raw = RbConfig::CONFIG[flag_key].to_s
    # Drop unexpanded Make vars like $(cflags)/$(DEFS) — shell would treat $(cflags) as command subst
    raw = raw.gsub(/\$\([^)]*\)/, " ")
    cleaned = raw.split.reject do |f|
      f.include?("/data/data/") ||
        f.include?("android-support") ||
        f.start_with?("-isystem") ||
        f.start_with?("-Wl,-rpath") ||
        f.start_with?("-Wl,-rpath,") ||
        f == "-Wl,--enable-new-dtags" ||
        f == "-rdynamic" ||
        f == "-Wl,-export-dynamic" ||
        f.start_with?("$(")
    end
    RbConfig::CONFIG[flag_key] = RbConfig::MAKEFILE_CONFIG[flag_key] = cleaned.join(" ")
  end

  %w[LIBS LIBRUBYARG LIBRUBYARG_SHARED SOLIBS].each do |flag_key|
    next unless RbConfig::CONFIG[flag_key]
    cleaned = RbConfig::CONFIG[flag_key].to_s.split.reject do |f|
      %w[-lpthread -lrt -ldl -lutil -pthread].include?(f)
    end
    RbConfig::CONFIG[flag_key] = RbConfig::MAKEFILE_CONFIG[flag_key] = cleaned.join(" ")
  end

  extra_ld = "-L\#{stage}/lib"
  %w[LDFLAGS DLDFLAGS].each do |flag_key|
    RbConfig::CONFIG[flag_key] = [extra_ld, RbConfig::CONFIG[flag_key]].join(" ").strip
    RbConfig::MAKEFILE_CONFIG[flag_key] = RbConfig::CONFIG[flag_key]
  end

  ENV["CC"] = cc
  ENV["CXX"] = cxx
  ENV["AR"] = ar
  ENV["LD"] = ld
  ENV["RANLIB"] = ranlib
  ENV["STRIP"] = strip
  ENV["CPP"] = "\#{cc} -E"
  ENV["NOKOGIRI_USE_SYSTEM_LIBRARIES"] = "1"
  ENV["CPPFLAGS"] = [
    "-I\#{stage}/include",
    "-I\#{ruby_hdr}",
    "-I\#{ruby_arch_hdr}",
    "-I\#{stage}/include/libxml2",
    ENV["CPPFLAGS"],
  ].compact.join(" ")
  ENV["LDFLAGS"] = ["-L\#{stage}/lib", ENV["LDFLAGS"]].compact.join(" ")
  ENV["CFLAGS"] = [ENV.fetch("CFLAGS", "-fPIC -O2"), "-fPIC"].join(" ")
  ENV["PKG_CONFIG_PATH"] = File.join(stage, "lib", "pkgconfig")
  ENV["PKG_CONFIG_LIBDIR"] = File.join(stage, "lib", "pkgconfig")
PRELOAD

# Ensure mini_portile2 present (gumbo always builds from package sources)
begin
  require "mini_portile2"
rescue LoadError
  system(host_ruby, "-S", "gem", "install", "mini_portile2", "--no-document") || abort("need mini_portile2")
end

extconf_args = [
  "--use-system-libraries",
  "--disable-clean", # same idea as jekyllex extconf patch: no clean-ports / no android ruby
  "--with-opt-dir=#{stage}",
  "--with-xml2-include=#{stage}/include/libxml2",
  "--with-xml2-lib=#{stage}/lib",
  "--with-xslt-include=#{stage}/include",
  "--with-xslt-lib=#{stage}/lib",
  "--with-exslt-include=#{stage}/include",
  "--with-exslt-lib=#{stage}/lib",
  "--with-iconv-include=#{stage}/include",
  "--with-iconv-lib=#{stage}/lib",
  "--with-zlib-include=#{stage}/include",
  "--with-zlib-lib=#{stage}/lib",
  "--disable-static",
  "--prevent-strip",
  "--srcdir=#{ext_dir}",
]

puts "Loading target RbConfig from #{rbconfig_path}"
puts "Running extconf as real process (srcdir=#{ext_dir}) ..."
Dir.chdir(ext_dir) do
  cmd = [host_ruby, "-r", preload, "extconf.rb", *extconf_args]
  puts "+ #{Shellwords.join(cmd)}"
  abort "extconf failed" unless system(host_ruby, "-r", preload, "extconf.rb", *extconf_args)

  makefile = File.join(ext_dir, "Makefile")
  abort "Makefile not created" unless File.file?(makefile)

  # Harden Makefile: host RUBY, never stage/android ruby; ensure DLLIB set
  mk = File.read(makefile)
  mk.gsub!(%r{^RUBY\s*=\s*.*$}, "RUBY = #{host_ruby}")
  mk.gsub!(%r{^ruby\s*=\s*.*$}, "ruby = #{host_ruby}")
  # Drop clean-ports chain if still present (belt + suspenders vs jekyllex patch)
  mk.gsub!(/^all: clean-ports\n/, "all: $(DLLIB)\n")
  mk.gsub!(/^clean-ports:.*\n(?:\t.*\n)*/, "")
  File.write(makefile, mk)

  # Sanity: DLLIB / TARGET must be set
  unless mk.match?(/^DLLIB\s*=\s*\S+/)
    warn "Makefile excerpt (DLLIB/TARGET/srcdir):"
    mk.each_line { |l| warn l if l =~ /DLLIB|TARGET|srcdir/ }
    abort "Makefile has empty DLLIB — extconf did not find sources"
  end

  make = ENV.fetch("MAKE", "make")
  jobs = ENV.fetch("JOBS", "4")
  puts "Building with #{make} -j#{jobs} ..."
  abort "make failed" unless system(make, "-j#{jobs}")
end

so = Dir.glob(File.join(ext_dir, "nokogiri.{so,bundle}")).first ||
  Dir.glob(File.join(ext_dir, "**", "nokogiri.{so,bundle}")).first ||
  Dir.glob(File.join(nokogiri_src, "lib", "**", "nokogiri.{so,bundle}")).first
abort "compiled nokogiri.so not found under #{ext_dir}" unless so

out_dir = File.join(root, "out", gem_platform)
FileUtils.mkdir_p(out_dir)
out_so = File.join(out_dir, "nokogiri.so")
FileUtils.cp(so, out_so)

if File.executable?(strip)
  system(strip, "--strip-unneeded", out_so)
end

# Remove host-absolute RUNPATH/RPATH so device uses LD_LIBRARY_PATH / usr/lib
patchelf = File.join(File.dirname(ar), "llvm-patchelf")
# NDK may not ship patchelf; try chrpath / delete via llvm-objcopy no-op
if File.executable?(patchelf)
  system(patchelf, "--remove-rpath", out_so)
elsif system("which", "patchelf", out: File::NULL, err: File::NULL)
  system("patchelf", "--remove-rpath", out_so)
end

puts "OK: #{out_so}"
puts "size=#{File.size(out_so)}"
system("file", out_so) if system("which", "file", out: File::NULL, err: File::NULL)

readelf = File.join(File.dirname(ar), "llvm-readelf")
if File.executable?(readelf)
  system(readelf, "-h", out_so)
  system(readelf, "-d", out_so)
elsif system("which", "readelf", out: File::NULL, err: File::NULL)
  system("readelf", "-h", out_so)
  system("readelf", "-d", out_so)
end
