name: Build

on:
  workflow_dispatch:
  push:
    branches: ["feature/**", "fix-ci"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, arm, i686, x86_64]
    steps:
      - uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r27c
          local-cache: false
      - run: echo "NDK=${{ steps.ndk.outputs.ndk-path }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.4"
      - run: gem install mini_portile2 --no-document
      - run: ./scripts/build.sh ${{ matrix.arch }}
      - uses: actions/upload-artifact@v7
        with:
          name: nokogiri-${{ matrix.arch }}
          path: |
            pkg/*.gem
            out/**/nokogiri.so
      - if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: logs-${{ matrix.arch }}
          path: nokogiri/ext/nokogiri/mkmf.log
          if-no-files-found: ignore
